language: node_js
node_js:
  - "14"
cache:
  yarn: true
script:
  - yarn test
  - make integration-test
deploy:
  edge: true
  provider: npm
  email: axyzxp@gmail.com
  api_key:
    secure: rbOAEgIHg0X4xImMkOcMsE+3wUIjvme6nStYrjnEILaqGFj3/1beAkgrjBVgqZnkpY2AzNXbf+8F4kA1a5KU2aQW+M+WektgRLmfZtrhauHlnsUmtJet4mZn/uXjM3rBUMckDUtf652WI+NOSgHN7AtYjI8MQ7rLtQacF3OIXfyMiJ7h4wmg/ktC4Fp4BMNnpxl2CH1x8S9KvL5AWkAYxWCdLKMYLwVTg3eZh3hhRX/q+GVJb8hIq+HyzI7rsF7CQGVrl/3f1kZYammjDK6vFcfkC7y+XsU73nRUrJg4JKQ3vzsjYLoQzsM8CXTCrFNI9/s6mrz07HGJWx4BhPam7tiDecxK5px1MfbQtZk/9btRA3BAnlRkeHmvgS13vj0a+qQG6a1/xOfeM+vtPp9iE6JKB6F3Dc15wlPI8OCHukxkkpq0OOw92KuQvKhRibbgdaEhIFbWFhT7bHkTouVO63vCV8qhlN67who1cD1tA5xYEO39rGJnmZTt/37LbmGFBmiKXpzb2/hUQTk+g4LhBEcBgGX0YHAyxOsuE/ahE9RT7WbKj3EhHVtN4F2nXXrAYbnRB+frw7MhHtcIsIs0oG0l3YjMtarWekAjd/WMHxBeIlesBOWewcUu4NYtUC9yII3Tu8N4+YmAoQVzrU/c0FD2Nm8+U9NUM7drA0lQ7IA=
  skip_cleanup: true
  on:
    tags: true
    repo: utilitycss/atomic
